const fs = require('fs');
let c = fs.readFileSync('index.html', 'utf8');

const novoFaq = '<section><div class="container"><div class="section-eyebrow">Duvidas frequentes</div><h2 class="section-title">Respondemos as mais comuns</h2><div class="faq-list"><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Como funciona o rastreamento?<span class="faq-icon">+</span></button><div class="faq-a">A Tag+ usa tecnologia Bluetooth e a rede de dispositivos proximos para localizar em tempo real, sem precisar de internet propria.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Para quais dispositivos posso usar a Tag+?<span class="faq-icon">+</span></button><div class="faq-a">Veiculos, pessoas e pets. Uma unica tag serve para tudo.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Como entro no TrackingYou Club?<span class="faq-icon">+</span></button><div class="faq-a">Ao adquirir a Tag+ voce ja faz parte automaticamente. Seu painel e criado na hora da compra.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Como recebo comissoes?<span class="faq-icon">+</span></button><div class="faq-a">Creditadas no seu painel e pagas via PIX na chave cadastrada no TrackingYou Club.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Valor minimo para saque?<span class="faq-icon">+</span></button><div class="faq-a">R$ 100,00 via PIX em ate 2 dias uteis.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Quantos niveis de comissao?<span class="faq-icon">+</span></button><div class="faq-a">3 niveis: 20% venda direta, 5% segundo nivel, 3% terceiro nivel.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Como acesso meu painel?<span class="faq-icon">+</span></button><div class="faq-a">Link enviado por email apos a compra. Login com CPF/CNPJ e senha criada na compra.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Tag funciona sem internet?<span class="faq-icon">+</span></button><div class="faq-a">Sim! Via Bluetooth usando dispositivos proximos ao redor.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Qual a garantia?<span class="faq-icon">+</span></button><div class="faq-a">3 meses contra defeitos de fabricacao. Certificacao IP67 resistente a agua.</div></div><div class="faq-item"><button class="faq-q" onclick="toggleFaq(this)">Como funciona apos 1 ano?<span class="faq-icon">+</span></button><div class="faq-a">1 ano incluso na compra. Apos isso plano basico gratuito ou premium a partir de R$ 9,99/mes.</div></div></div></div></section>';

const fi = c.lastIndexOf('<section', c.indexOf('D\u00favidas frequentes'));
const fe = c.indexOf('</section>', fi) + 10;

c = c.slice(0, fi) + novoFaq + c.slice(fe);

fs.writeFileSync('index.html', c);
console.log('OK!');
console.log('tamanho:', c.length);
console.log('Duvidas:', (c.match(/D.vidas frequentes/g)||[]).length);
